import jinxes from "../generated/jinxes.json" with { type: "json" };
import nightsheet from "../generated/nightsheet.json" with { type: "json" };
import roles from "../generated/roles.json" with { type: "json" };
import type { ScriptCharacter } from "../generated/script-schema";

const jinxMap = new Map(jinxes.map((entry) => [entry.id, entry.jinx]));
const unfilledRoles = roles as ScriptCharacter[];

const filledRoles = unfilledRoles.map((role) => ({
  ...role,
  jinxes: jinxMap.get(role.id),
}));

export { nightsheet as nightOrder, filledRoles as roles };

// Copied from data.json in the official app, as this isn't published anywhere.
// Most of this could be reconstructed from the roles.json, but there are differences (like TB's night order).
export const editions = [
  {
    id: "tb",
    name: "Trouble Brewing",
    color: "#AB0D27",
    themes: 6,
    level: "beginner",
    isOfficial: true,
    roles: [
      "washerwoman",
      "librarian",
      "investigator",
      "chef",
      "empath",
      "fortuneteller",
      "undertaker",
      "monk",
      "ravenkeeper",
      "virgin",
      "slayer",
      "soldier",
      "mayor",
      "butler",
      "drunk",
      "recluse",
      "saint",
      "poisoner",
      "spy",
      "baron",
      "scarletwoman",
      "imp",
    ],
    firstNight: [
      "dusk",
      "angel",
      "buddhist",
      "toymaker",
      "stormcatcher",
      "bureaucrat",
      "thief",
      "apprentice",
      "barista",
      "minioninfo",
      "demoninfo",
      "poisoner",
      "spy",
      "washerwoman",
      "librarian",
      "investigator",
      "chef",
      "empath",
      "fortuneteller",
      "butler",
      "dawn",
    ],
    otherNight: [
      "dusk",
      "duchess",
      "toymaker",
      "bureaucrat",
      "thief",
      "barista",
      "bonecollector",
      "harlot",
      "poisoner",
      "monk",
      "spy",
      "scarletwoman",
      "imp",
      "tor",
      "ravenkeeper",
      "undertaker",
      "empath",
      "fortuneteller",
      "butler",
      "dawn",
    ],
  },
  {
    id: "bmr",
    name: "Bad Moon Rising",
    color: "#EC9834",
    themes: 6,
    level: "intermediate",
    isOfficial: true,
    roles: [
      "grandmother",
      "sailor",
      "chambermaid",
      "exorcist",
      "innkeeper",
      "gambler",
      "gossip",
      "courtier",
      "professor",
      "minstrel",
      "tealady",
      "pacifist",
      "fool",
      "goon",
      "lunatic",
      "tinker",
      "moonchild",
      "godfather",
      "devilsadvocate",
      "assassin",
      "mastermind",
      "zombuul",
      "pukka",
      "shabaloth",
      "po",
    ],
    firstNight: [
      "dusk",
      "angel",
      "buddhist",
      "toymaker",
      "stormcatcher",
      "bureaucrat",
      "thief",
      "apprentice",
      "barista",
      "minioninfo",
      "lunatic",
      "demoninfo",
      "sailor",
      "courtier",
      "godfather",
      "devilsadvocate",
      "pukka",
      "grandmother",
      "chambermaid",
      "dawn",
    ],
    otherNight: [
      "dusk",
      "duchess",
      "toymaker",
      "bureaucrat",
      "thief",
      "barista",
      "bonecollector",
      "harlot",
      "sailor",
      "innkeeper",
      "courtier",
      "gambler",
      "devilsadvocate",
      "lunatic",
      "exorcist",
      "zombuul",
      "pukka",
      "shabaloth",
      "po",
      "assassin",
      "godfather",
      "professor",
      "gossip",
      "tinker",
      "moonchild",
      "grandmother",
      "tor",
      "chambermaid",
      "dawn",
    ],
  },
  {
    id: "snv",
    name: "Sects & Violets",
    color: "#8D57AA",
    themes: 6,
    level: "intermediate",
    isOfficial: true,
    roles: [
      "clockmaker",
      "dreamer",
      "snakecharmer",
      "mathematician",
      "flowergirl",
      "towncrier",
      "oracle",
      "savant",
      "seamstress",
      "philosopher",
      "artist",
      "juggler",
      "sage",
      "mutant",
      "barber",
      "sweetheart",
      "klutz",
      "witch",
      "cerenovus",
      "pithag",
      "eviltwin",
      "fanggu",
      "vigormortis",
      "nodashii",
      "vortox",
    ],
    firstNight: [
      "dusk",
      "angel",
      "buddhist",
      "toymaker",
      "stormcatcher",
      "bureaucrat",
      "thief",
      "apprentice",
      "barista",
      "minioninfo",
      "demoninfo",
      "philosopher",
      "snakecharmer",
      "eviltwin",
      "witch",
      "cerenovus",
      "clockmaker",
      "dreamer",
      "seamstress",
      "mathematician",
      "dawn",
    ],
    otherNight: [
      "dusk",
      "duchess",
      "toymaker",
      "bureaucrat",
      "thief",
      "barista",
      "bonecollector",
      "harlot",
      "philosopher",
      "snakecharmer",
      "witch",
      "cerenovus",
      "pithag",
      "fanggu",
      "vigormortis",
      "nodashii",
      "vortox",
      "tor",
      "barber",
      "sweetheart",
      "sage",
      "dreamer",
      "flowergirl",
      "towncrier",
      "oracle",
      "seamstress",
      "juggler",
      "mathematician",
      "dawn",
    ],
  },
];
