import type { LocalScriptDefinition } from "../../types/site";

export const WORLD_CUP_25: LocalScriptDefinition[] = [
  {
    id: "1daymore",
    title: "1 Day More",
    character: "nightwatchman",
    color: "#481941",
    botcScripts: { scriptId: 6741, versionId: "1.0.1", pk: 11665 },
    getScript: () => import("./1daymore.json").then((m) => m.default),
  },
  {
    id: "beautifulhouse",
    title: "This Is Not My Beautiful House",
    character: "amnesiac",
    color: "#481941",
    botcScripts: { scriptId: 6707, versionId: "2.0.0", pk: 17107 },
    getScript: () => import("./beautifulhouse.json").then((m) => m.default),
  },
  {
    id: "binarysupernovae",
    title: "Binary Supernovae",
    character: "summoner",
    color: "#481941",
    botcScripts: { scriptId: 6457, versionId: "3.0.1", pk: 15603 },
    getScript: () => import("./binarysupernovae.json").then((m) => m.default),
  },
  {
    id: "buyersremorse",
    title: "Buyer's Remorse",
    character: "noble",
    color: "#481941",
    botcScripts: { scriptId: 6716, versionId: "3.0.1", pk: 18646 },
    getScript: () => import("./buyersremorse.json").then((m) => m.default),
  },
  {
    id: "deadcouncil",
    title: "Council of the Dead",
    character: "oracle",
    botcScripts: { scriptId: 6742, versionId: "1.1.0", pk: 11657 },
    color: "#481941",
    getScript: () => import("./deadcouncil.json").then((m) => m.default),
  },
  {
    id: "deadpeople",
    title: "I see dead people",
    character: "sage",
    color: "#481941",
    botcScripts: { scriptId: 6799, versionId: "1.0.0", pk: 11463 },
    getScript: () => import("./deadpeople.json").then((m) => m.default),
  },
  {
    id: "djinnsbargain",
    title: "The Djinn's Bargain",
    character: "djinn",
    color: "#481941",
    botcScripts: { scriptId: 6146, versionId: "9.0.0", pk: 11892 },
    getScript: () => import("./djinnsbargain.json").then((m) => m.default),
  },
  {
    id: "offwizard",
    title: "Off to see the Wizard",
    character: "wizard",
    color: "#481941",
    botcScripts: { scriptId: 6679, versionId: "1.0.2", pk: 12936 },
    getScript: () => import("./offwizard.json").then((m) => m.default),
  },
  {
    id: "phantomdetectives",
    title: "The Phantom Detectives",
    character: "banshee",
    color: "#481941",
    botcScripts: { scriptId: 6717, versionId: "5.2.1", pk: 12524 },
    getScript: () => import("./phantomdetectives.json").then((m) => m.default),
  },
  {
    id: "riverstyx",
    title: "The River Styx",
    character: "ferryman",
    color: "#481941",
    botcScripts: { scriptId: 6026, versionId: "1.2.0", pk: 11949 },
    getScript: () => import("./riverstyx.json").then((m) => m.default),
  },
  {
    id: "seat7",
    title: "The Ballad of Seat 7",
    character: "scarletwoman",
    color: "#481941",
    botcScripts: { scriptId: 6687, versionId: "6.0.0", pk: 13359 },
    getScript: () => import("./seat7.json").then((m) => m.default),
  },
  {
    id: "stowedaway",
    title: "Stowed Away",
    character: "apprentice",
    color: "#481941",
    botcScripts: { scriptId: 6714, versionId: "4.0.0", pk: 16499 },
    getScript: () => import("./stowedaway.json").then((m) => m.default),
  },
  {
    id: "trainedkiller",
    title: "Trained Killer",
    character: "lilmonsta",
    color: "#481941",
    botcScripts: { scriptId: 6705, versionId: "1.2.0", pk: 12347 },
    getScript: () => import("./trainedkiller.json").then((m) => m.default),
  },
  {
    id: "warrens",
    title: "The Warrens",
    character: "undertaker",
    color: "#481941",
    botcScripts: { scriptId: 6773, versionId: "4.0.0", pk: 12694 },
    getScript: () => import("./warrens.json").then((m) => m.default),
  },
  {
    id: "witchhunt",
    title: "Witch Hunt",
    character: "witch",
    color: "#481941",
    botcScripts: { scriptId: 8749, versionId: "1.0.0", pk: 15070 },
    getScript: () => import("./witchhunt.json").then((m) => m.default),
  },
  {
    id: "wonders",
    title: "show me wonders",
    character: "alhadikhia",
    color: "#481941",
    botcScripts: { scriptId: 6779, versionId: "1.1.0", pk: 11963 },
    getScript: () => import("./wonders.json").then((m) => m.default),
  },
];
