export function normaliseCharacterId(id: string): string {
  return id.toLowerCase().replace(/[_-]/g, "");
}

export const ORDERED_CHARACTER_LIST = [
  // TB
  "washerwoman",
  "librarian",
  "investigator",
  "chef",
  "empath",
  "fortuneteller",
  "undertaker",
  "monk",
  "ravenkeeper",
  "virgin",
  "slayer",
  "soldier",
  "mayor",
  "butler",
  "drunk",
  "recluse",
  "saint",
  "poisoner",
  "spy",
  "scarletwoman",
  "baron",
  "imp",
  // SnV
  "clockmaker",
  "dreamer",
  "snakecharmer",
  "mathematician",
  "flowergirl",
  "towncrier",
  "oracle",
  "savant",
  "seamstress",
  "philosopher",
  "artist",
  "juggler",
  "sage",
  "mutant",
  "sweetheart",
  "barber",
  "klutz",
  "eviltwin",
  "witch",
  "cerenovus",
  "pithag",
  "fanggu",
  "vigormortis",
  "nodashii",
  "vortox",
  // BMR
  "grandmother",
  "sailor",
  "chambermaid",
  "exorcist",
  "innkeeper",
  "gambler",
  "gossip",
  "courtier",
  "professor",
  "minstrel",
  "tealady",
  "pacifist",
  "fool",
  "tinker",
  "moonchild",
  "goon",
  "lunatic",
  "godfather",
  "devilsadvocate",
  "assassin",
  "mastermind",
  "zombuul",
  "pukka",
  "shabaloth",
  "po",
  // Base travellers
  "apprentice",
  "barista",
  "bureaucrat",
  "beggar",
  "bishop",
  "bonecollector",
  "butcher",
  "deviant",
  "gunslinger",
  "harlot",
  "judge",
  "matron",
  "scapegoat",
  "thief",
  "voudon",
  // Base fabled
  "angel",
  "buddhist",
  "djinn",
  "doomsayer",
  "duchess",
  "fibbin",
  "fiddler",
  "hellslibrarian",
  "revolutionary",
  "sentinel",
  "spiritofivory",
  "toymaker",
  // Carousel townsfolk
  "acrobat",
  "alchemist",
  "alsaahir",
  "amnesiac",
  "atheist",
  "balloonist",
  "banshee",
  "bountyhunter",
  "cannibal",
  "choirboy",
  "cultleader",
  "engineer",
  "farmer",
  "fisherman",
  "general",
  "highpriestess",
  "huntsman",
  "king",
  "knight",
  "lycanthrope",
  "magician",
  "nightwatchman",
  "noble",
  "pixie",
  "poppygrower",
  "preacher",
  "princess",
  "shugenja",
  "steward",
  "villageidiot",
  // Carousel outsiders
  "damsel",
  "golem",
  "hatter",
  "heretic",
  "hermit",
  "ogre",
  "plaguedoctor",
  "politician",
  "puzzlemaster",
  "snitch",
  "zealot",
  // Carousel minions
  "boffin",
  "boomdandy",
  "fearmonger",
  "goblin",
  "harpy",
  "marionette",
  "mezepheles",
  "organgrinder",
  "psychopath",
  "summoner",
  "vizier",
  "widow",
  "wizard",
  "wraith",
  "xaan",
  // Carousel demons
  "alhadikhia",
  "kazali",
  "legion",
  "leviathan",
  "lilmonsta",
  "lleech",
  "lordoftyphon",
  "ojo",
  "riot",
  "yaggababble",
  // Carousel travellers
  "cacklejack",
  "gangster",
  "gnome",
  // Carousel fabled
  "bootlegger",
  "deusexfiasco",
  "ferryman",
  "gardener",
  "stormcatcher",
  // Characters released after the Carousel, in release order
  "bigwig",
  "tor",
  "zenomancer",
  "hindu",
  "pope",
  "ventriloquist",
  "godofug",
  "knaves",
];

if (ORDERED_CHARACTER_LIST.length >= 240) {
  console.warn(
    `Build warning: character list for NS is nearing its limit (${ORDERED_CHARACTER_LIST.length}/${250}).`,
  );
}

if (ORDERED_CHARACTER_LIST.length >= 250) {
  throw new Error(
    `Build error: character list for NS is at its limit (${ORDERED_CHARACTER_LIST.length}/${250}).`,
  );
}

// The highest index that can be set in this array is [253] (length 254).
// This array is offset by 1 compared to the actual byte encodings as 0x00 is
// the meta section. 0xFF is reserved for arbitrary JSON (custom characters),
// which then makes the highest available value in this array 253.
ORDERED_CHARACTER_LIST.length = 254;
ORDERED_CHARACTER_LIST[251] = "minioninfo";
ORDERED_CHARACTER_LIST[252] = "demoninfo";
ORDERED_CHARACTER_LIST[253] = "dusk";
ORDERED_CHARACTER_LIST[250] = "dawn"; // Dawn is at the start because of a pre-existing bug in the initial special night order implementation.
