name: Script schema auto-update

on:
  schedule:
    # Friday evenings NZ time.
    # Most app releases happen late in the week.
    - cron: "13 6 * * 5"
  workflow_dispatch:

jobs:
  update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Update schema
        run: |
          mkdir -p setup
          curl -fsSL https://raw.githubusercontent.com/ThePandemoniumInstitute/botc-release/main/script-schema.json -o setup/schema.json
          git add setup/schema.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: |
            setup/schema.json
          commit-message: "[Auto] Update JSON schema"
          branch: auto-update/schema
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "[Auto] Update script JSON schema"
          body: |
            Automatic update for the script schema.
