name: Monthly scripts auto-update

on:
  schedule:
    # First day of the month.
    - cron: "0 7 1 * *"
  workflow_dispatch:

jobs:
  update-monthly-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Download monthly scripts
        run: node setup/download-monthly-scripts.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: |
            src/scripts/monthly/*.json
          commit-message: "[Auto] Update monthly scripts"
          branch: auto-update/monthly-scripts
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "[Auto] Update monthly scripts"
          body: |
            Automatic update for the script of the month.

            > [!WARNING]
            > You may need to update `src/scripts/monthly/index.ts` if there
            > are changes to a script, or if there are new scripts added.
